name: Enhanced Digital Forge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Validate .autodev structure
      run: python tools/validate.py
    
  nextjs-build:
    runs-on: ubuntu-latest
    needs: validate-structure
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build Next.js
      run: npm run build
    - name: Run linting
      run: npm run lint
  
  seo-validation:
    runs-on: ubuntu-latest
    needs: nextjs-build
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build for production
      run: npm run build
    - name: Validate sitemap
      run: |
        if [ -f "app/sitemap.ts" ]; then
          echo "✅ Sitemap found"
        else
          echo "❌ Sitemap missing"
          exit 1
        fi
    - name: Validate robots.txt
      run: |
        if [ -f "app/robots.ts" ]; then
          echo "✅ Robots.txt found"
        else
          echo "❌ Robots.txt missing"
          exit 1
        fi
  
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run security audit
      run: npm audit --audit-level moderate
    - name: Check for secrets
      run: |
        if grep -r "sk-" . --exclude-dir=node_modules --exclude-dir=.git; then
          echo "❌ Potential secrets found"
          exit 1
        else
          echo "✅ No secrets detected"
        fi